docker_root_path: "/srv/docker"

# Portainer configuration
portainer:
  install: true
  docker_network_name: "proxy"
  config_dir: "{{ docker_root_path }}/portainer"
  # Traefik integration settings
  traefik_labels:
    traefik.enable: "true"
    # Skip below if traefik.enable is false
    traefik.http.routers.portainer.rule: "Host(`portainer.farshaddavoudi.ir`)"
    traefik.http.routers.portainer.entrypoints: "https"
    traefik.http.routers.portainer.tls: true
    traefik.http.services.portainer.loadbalancer.server.port: "9000"

# Docker Role Variables - Use Ubuntu's repository instead of Docker's official repository
# This avoids issues with blocked access to download.docker.com in Iran
docker_edition: 'ce'
docker_service_manage: true
docker_service_state: started
docker_service_enabled: true
docker_add_repo: false  # Disable Docker's official repository
docker_packages_state: present
docker_install_compose_plugin: false  # Don't install compose plugin since we're using Ubuntu packages
docker_install_compose: false  # Install traditional docker-compose

# Install Docker from Ubuntu's repository
docker_packages:
  - docker.io
  - docker-compose

# Docker daemon configuration for Iran
docker_daemon_options:
  insecure-registries:
    - "docker.arvancloud.ir"
  registry-mirrors:
    - "https://registry-1.docker.io"
    - "https://docker.arvancloud.ir"
    - "https://docker.mirrors.sjtug.sjtu.edu.cn"
    - "https://mirror.baidubce.com"
  dns:
    - "8.8.8.8"
    - "1.1.1.1"

# Clean up obsolete packages
docker_obsolete_packages:
  - docker
  - docker.io
  - docker-engine
  - docker-doc
  - docker-compose
  - docker-compose-v2
  - podman-docker
  - containerd
  - runc