docker_root_path: "/srv/docker"

# Portainer configuration
portainer:
  install: true
  docker_network_name: "proxy"
  config_dir: "{{ docker_root_path }}/portainer"
  # Traefik integration settings
  traefik_labels:
    enabled: false
    traefik.http.routers.portainer.rule: "Host(`portainer.farshaddavoudi.ir`)"
    traefik.http.routers.portainer.entrypoints: "https"
    traefik.http.routers.portainer.tls: true
    traefik.http.services.portainer.loadbalancer.server.port: "9000"

# Docker Role Variables - Use Ubuntu's repository for Docker engine only
# Install Docker Compose manually to get the latest version
docker_edition: 'ce'
docker_service_manage: true
docker_service_state: started
docker_service_enabled: true
docker_add_repo: false  # Disable Docker's official repository
docker_packages_state: present
docker_install_compose_plugin: true 
docker_install_compose: true 

# Install only Docker engine from Ubuntu's repository
docker_packages:
  - docker.io

# Docker daemon configuration for Iran - multiple mirrors for fallback
docker_daemon_options:
  registry-mirrors:
    - "https://docker.arvancloud.ir"
    - "https://docker.mirrors.sjtug.sjtu.edu.cn"
    - "https://registry-1.docker.io"
    - "https://mirror.baidubce.com"
  insecure-registries:
    - "docker.arvancloud.ir"

# Clean up obsolete packages
docker_obsolete_packages:
  - docker
  - docker.io
  - docker-engine
  - docker-doc
  - docker-compose-v2
  - podman-docker
  - containerd
  - runc