# Usage: 
# ansible-galaxy install -r requirements.yml
# ansible-playbook alloy-config-windows-pb.yml
---
- name: Install and Configure Grafana Alloy on Windows
  hosts: alloy_win_servers
  become: false
  become_method: runas

  tasks:
    - name: Check if Alloy is already installed
      win_shell: |
        try {
          $version = & "C:\Program Files\Grafana Agent\alloy.exe" --version
          Write-Output $version
        } catch {
          Write-Output "Not installed"
          exit 1
        }
      register: alloy_check
      failed_when: false
      changed_when: false

    - name: Install Grafana Alloy (if not already installed)
      block:
        - name: Create installer cache directory
          win_file:
            path: "C:\\temp\\alloy_installers"
            state: directory

        - name: Check if installer already exists in cache
          win_stat:
            path: "C:\\temp\\alloy_installers\\alloy-installer-{{ alloy_version }}.zip"
          register: installer_cached

        - name: Download Grafana Alloy Windows installer
          win_get_url:
            url: "https://github.com/grafana/alloy/releases/download/{{ alloy_version }}/alloy-installer-windows-amd64.exe.zip"
            dest: "C:\\temp\\alloy_installers\\alloy-installer-{{ alloy_version }}.zip"
            force: false
          when: not installer_cached.stat.exists

        - name: Create temporary directory for extraction
          win_tempfile:
            state: directory
            suffix: alloy_extract
          register: extract_dir

        - name: Extract installer from zip
          win_unzip:
            src: "C:\\temp\\alloy_installers\\alloy-installer-{{ alloy_version }}.zip"
            dest: "{{ extract_dir.path }}"

        - name: Install Grafana Alloy
          win_package:
            path: "{{ extract_dir.path }}\\alloy-installer-windows-amd64.exe"
            arguments: '/S'
            state: present
            wait_for_children: true

        - name: Clean up extraction directory
          win_file:
            path: "{{ extract_dir.path }}"
            state: absent

      when: alloy_check.rc != 0

    - name: Display Alloy version (if already installed)
      debug:
        msg: "Alloy is already installed: {{ alloy_check.stdout }}"
      when: alloy_check.rc == 0

    - name: Create Alloy configuration directory
      win_file:
        path: "{{ alloy_config_dir }}"
        state: directory

    - name: Stop Alloy service before configuration
      win_service:
        name: "Alloy"
        state: stopped
      ignore_errors: true

    - name: Configure Alloy environment variables
      win_template:
        src: alloy-env-windows.j2
        dest: "C:\\Program Files\\Grafana Agent\\alloy-config.yml"
      notify: restart alloy windows

    - name: Create Windows Event Log configuration
      win_template:
        src: windows-events.alloy.j2
        dest: "{{ alloy_config_dir }}\\windows-events.alloy"
      notify: restart alloy windows

    - name: Create IIS logs configuration (if IIS is installed)
      block:
        - name: Check if IIS is installed (method 1)
          win_feature:
            name: "IIS-WebServer"
            state: present
          register: iis_check_ws
          check_mode: true
          ignore_errors: true

        - name: Check if IIS is installed (method 2 - Windows Server)
          win_feature:
            name: "Web-Server"
            state: present
          register: iis_check_server
          check_mode: true
          ignore_errors: true
          when: iis_check_ws is failed

        - name: Check if IIS service exists (fallback method)
          win_service:
            name: "W3SVC"
          register: iis_service_check
          ignore_errors: true
          when: iis_check_ws is failed and (iis_check_server is skipped or iis_check_server is failed)

        - name: Determine if IIS is available
          set_fact:
            iis_available: >-
              {{ 
                (iis_check_ws.success is defined and iis_check_ws.success) or
                (iis_check_server.success is defined and iis_check_server.success) or
                (iis_service_check.exists is defined and iis_service_check.exists)
              }}

        - name: Create IIS logs configuration file
          win_template:
            src: iis-logs.alloy.j2
            dest: "{{ alloy_config_dir }}\\iis-logs.alloy"
          when: iis_available | default(false)
          notify: restart alloy windows

    - name: Create application logs configuration
      win_template:
        src: app-logs-windows.alloy.j2
        dest: "{{ alloy_config_dir }}\\app-logs.alloy"
      notify: restart alloy windows

    - name: Create Docker logs configuration (if Docker exists)
      block:
        - name: Check if Docker is installed
          win_shell: |
            try {
              docker --version
              exit 0
            } catch {
              exit 1
            }
          register: docker_check
          failed_when: false
          changed_when: false

        - name: Create Docker logs configuration file
          win_template:
            src: docker-windows.alloy.j2
            dest: "{{ alloy_config_dir }}\\docker.alloy"
          when: docker_check.rc == 0
          notify: restart alloy windows

    - name: Update Alloy service configuration
      win_service:
        name: "Alloy"
        start_mode: auto
        state: started

  handlers:
    - name: restart alloy windows
      win_service:
        name: "Alloy"
        state: restarted

  post_tasks:
    - name: Wait for Alloy to start
      win_wait_for:
        port: "{{ alloy_ui_port }}"
        host: "127.0.0.1"
        timeout: 60

    - name: Verify Alloy service status
      win_service:
        name: "Alloy"
      register: alloy_status

    - name: Display Alloy status
      debug:
        msg: "Alloy service is {{ alloy_status.state }}"

    - name: Display Alloy UI URL
      debug:
        msg: "Alloy UI available at: http://{{ ansible_host }}:{{ alloy_ui_port }}"
