# Make sure the community.docker collection is installed:
# `ansible-galaxy collection install community.docker`
---
- name: Install Docker
  hosts: docker_servers
  become: true
    
  pre_tasks:
    - name: Check for stuck apt processes
      shell: ps aux | grep -E "apt-get|dpkg|unattended-upgrade" | grep -v grep
      register: apt_processes
      changed_when: false
      failed_when: false

    - name: Kill stuck apt processes if found
      shell: pkill -f "apt-get|dpkg|unattended-upgrade" || true
      when: apt_processes.stdout_lines | length > 0
      changed_when: false
      failed_when: false

    - name: Remove apt lock files if they exist
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /var/lib/apt/lists/lock
        - /var/cache/apt/archives/lock
        - /var/lib/dpkg/lock
        - /var/lib/dpkg/lock-frontend
      failed_when: false
      when: apt_processes.stdout_lines | length > 0

    - name: Ensure python3-pip is installed
      apt:
        name: python3-pip
        state: present
        update_cache: true

    - name: Install Docker SDK for Python via apt
      apt:
        name: python3-docker
        state: present
      register: apt_docker_result
      failed_when: false

    - name: Install Docker SDK via pip using accessible mirror (fallback)
      pip:
        name: docker
        state: present
        extra_args: --break-system-packages --index-url https://pypi.tuna.tsinghua.edu.cn/simple/ --trusted-host pypi.tuna.tsinghua.edu.cn
      when: apt_docker_result.failed | default(false)

  roles:
    - role: geerlingguy.docker

  post_tasks:
    - name: Install docker-compose via apt
      apt:
        name: docker-compose
        state: present

    - name: Ensure Docker daemon configuration is valid
      copy:
        content: |
          {
            "registry-mirrors": [
              "https://docker.arvancloud.ir",
              "https://docker.mirrors.sjtug.sjtu.edu.cn",
              "https://registry-1.docker.io",
              "https://mirror.baidubce.com"
            ],
            "insecure-registries": [
              "docker.arvancloud.ir"
            ]
          }
        dest: /etc/docker/daemon.json
        mode: '0644'
        backup: true
      notify: restart docker
      when: docker_daemon_options is defined

    - name: Create Portainer data directory
      file:
        path: "{{ portainer.config_dir }}/data"
        state: directory
        mode: '0755'
      when: portainer.install

    - name: Ensure proxy network exists
      community.docker.docker_network:
        name: "{{ portainer.docker_network_name }}"
        state: present
      when: portainer.install

    - name: Pull Portainer image
      community.docker.docker_image:
        name: portainer/portainer-ce:latest
        source: pull
      when: portainer.install

    - name: Run Portainer container
      community.docker.docker_container:
        name: portainer
        image: portainer/portainer-ce:latest
        state: started
        restart_policy: unless-stopped
        ports:
          - "8000:8000"
          - "9443:9443"
          - "9000:9000"
        volumes:
          - "{{ docker_root_path }}:{{ docker_root_path }}"  # This ensures /srv/docker on host is visible inside Portainer
          - "{{ portainer.config_dir }}/data:/data"
          - /var/run/docker.sock:/var/run/docker.sock
        networks:
          - name: "{{ portainer.docker_network_name }}"
        labels: "{{ portainer.traefik_labels if portainer.traefik_labels.enable else {} }}"
        recreate: true
      when: portainer.install