---
- name: Setup Linux Servers
  hosts: linux_servers
  become: yes

  vars:
    install_git: false      # Set to false to skip git installation

  roles:
    - apt-fix

  tasks:
    - name: Set timezone to Asia/Tehran
      timezone:
        name: Asia/Tehran

    - name: Install Git
      apt:
        name: git
        state: present
        update_cache: yes
      when: install_git