---
# Comments can be seen at "/examples/vars.yml"

matrix_domain: farshaddavoudi.ir
matrix_homeserver_implementation: synapse
matrix_homeserver_generic_secret_key: 'a9Vx3TqL7zM2pYwRjKf8BdXeN6uGhQvWcEt1SbZoUlCmNrPiHsJkLgTfYdXqMwAzB'
matrix_playbook_reverse_proxy_type: playbook-managed-traefik
devture_systemd_docker_base_ipv6_enabled: true
postgres_connection_password: 'Aa123456'
traefik_container_network: 'proxy'
jitsi_enabled: true
exim_relay_enabled: false
matrix_homeserver_federation_enabled: false
matrix_playbook_docker_installation_enabled: false
matrix_playbook_ssl_enabled: true  # false if HAProxy handles TLS
traefik_container_image_tag: "v3.4"
matrix_rtc_enabled: true
matrix_element_call_enabled: true
matrix_coturn_turn_external_ip_address: "37.32.12.132"
matrix_coturn_container_network: host # Enable host networking for coturn to bypass Docker port publishing limitations
# Increase UDP port range for TURN relay
matrix_coturn_turn_udp_min_port: 49152
matrix_coturn_turn_udp_max_port: 49252
matrix_synapse_turn_uris:
  - turns:37.32.12.132?transport=udp
  - turns:37.32.12.132?transport=tcp
  - turn:37.32.12.132?transport=udp
  - turn:37.32.12.132?transport=tcp
matrix_coturn_additional_configuration: |
  verbose
  simple-log
  log-binding
  log-binding-errors
  fingerprint
  listening-ip=37.32.12.132
  listening-ip=0.0.0.0
  stale-nonce=600
  max-allocate-lifetime=3600
  channel-lifetime=600
  permission-lifetime=300