galaxy_info:
  author: farshaddavoudi
  description: A role to fix common apt package manager issues on Ubuntu/Debian systems
  company: ""
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
        - noble
    - name: Debian
      versions:
        - bullseye
        - bookworm
  galaxy_tags:
    - apt
    - package-manager
    - ubuntu
    - debian
    - system

dependencies: []
